# Generated by Django 5.2.17 on 2026-10-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_entrega', models.CharField(choices=[('12:00 - 13:00', '12:00 a 13:00 Hrs'), ('13:00 - 14:00', '13:00 a 14:00 Hrs'), ('14:00 - 15:00', '14:00 a 15:00 Hrs')], max_length=30)),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado por App Web'), ('EN_PREPARACION', 'En Preparación'), ('EN_RUTA', 'En Ruta'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=25)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatoMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Plato')),
                ('descripcion', models.TextField(verbose_name='Descripción del Plato')),
                ('dia_semana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes')], max_length=12, verbose_name='Día Asignado')),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre o Razón Social')),
                ('contacto', models.CharField(max_length=120, verbose_name='Persona de Contacto')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
